AWSTemplateFormatVersion: "2010-09-09"
Resources:
  LabMediumS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: '##CODENAME##-fixme-medium-s3-bucket'
      AccessControl: Private # hint: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html#cfn-s3-bucket-accesscontrol
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Info
          Value: '##CODENAME## FixMe Medium S3 Bucket'
        - Key: IaaSLabTemplateType
          Value: Medium